language: c
addons:
  apt:
    packages:
    - libasound2:i386
    - lib32z1
    - lib32bz2-1.0
    - libssl1.0.0:i386
    - libfreetype6:i386
script:
- if [[ ${TRAVIS_BRANCH} == "master" ]]; then make deploy; fi
env:
  global:
    secure: mfXtpbTRcVLzVpZpr7JLPDIx2QsIwnUxVilCAJpIevPASnDIdNjq7ngpf1J2MdcOY/mWJHZjAkhuC9KLQaMlq8oHP+Y9IQNaBLPbIm45/HScem73I2YA25AEfMY4T0ZzcCfotfN7Ln0dHIyuPEh3k+2J+6S9BTDD06G/7nmdcz7ijInSjpTQJxsGg8uOREEUITOFD5JrL4JZANV+BtQ3S/jdqnc7OQdBaKpOI2tSRAZC7KNlvgKAuRtFZ7qQ+wKThNHZm4Za8dd0R22pXhpLL0SR5CaoPq6R74wSIIazWKDPRsyQAN3hITQiW9sDH7cglBxjpidzh+vxaWrGxfwn9dk32FdTsbPd5t5pbdnW8/xx8dxhfrOV7QKhOAcyoDTLS8dbv8tDJvUUAAnCnNbhyh8v1a7JEYNq/rVCwsLKHkY9Kyr1xbTH4/yc7TL83Q1wzGcIobIf9Fojh47ses9BpLYX360c3Y/SHIQi56BRIZzeOyLrF/cDPTy0+Vj4JL5FQJ3C/Zs6ytsz05Kzaf8A9qkJ7XKzP1u5+4mA9g46gu8Hmmzu48QR1EcuMooX5W1CqKZy5ShtMvtmXslLdiE8Tg/xthj/C79quzGKp/h9lQzd8SE7LUBwhGY9N+otXObF9jxWpzmSt23U3vjRKe5oApZm6yGkav+MjG5uK5QBa8w=
