language: c
addons:
  apt:
    packages:
    - libasound2:i386
    - lib32z1
    - lib32bz2-1.0
    - libssl1.0.0:i386
    - libfreetype6:i386
script:
- if [[ ${TRAVIS_BRANCH} == "master" ]]; then make deploy; fi
env:
  global:
    secure: X+P0sbWTlmyfZkWviAfaAT1ITU/T4w4NVUnJiN/hXb5PscDnIv//Zgo+k1ayvLGvo/aAo5z3kStQ/Xj2KSREuCD3l6JxZEpE7bjuSn1TMCybPlWNj7dPMrr434u1obi17aCEhKsKhpq+ozSke8/HYaUkyOMEtWpQVh5ONRKbMjT+ELxq3HfCMLHzlAWjYunh2NvnZv/7Q4UioKapNavfOUzHysp7mtldQm+arEpyi1C8BDPN8f3LRUSJ9sk09OHV5WZ/q/9FeP3fjWXg++AiG9HmaDd4a2+tM1V4J9rUwnXhI0GigbPSUZomYI7toj6WXqoyLSo2IFQOqxzlR4Wt8n+OvkKobOdfm+q7oke/i027qA/pwlczrePl3kexfW0WWneNa4X1J6GC2YvvNXUGhB6hGDvrXiC5QeSap6zOrKLolAxY8sEX6O34x9fleRZ8ju9JHWkJ1kaO4/OKLBPjTtNXShzI5zVOJMwgeebSBVcDiySevFKkjvINYMAWXs5EkrtG3Q0Jx3yyweFwV8cDxmuwOgO1o0Cgo6TkLVmLheS2HU2duyFqOk3ACufstIOs2KSQYcrxLx3em253yAUAtQd5FBvoDd7oEKrYsimosTAsGeggNwKC2Vwb678T1dBecuteYPHlCq4W3MorlNjsjxTsnItltk1rGB/XXLU/rmc=
